server:
  port: 8085

spring:
  application:
    name: fund-transfer-service
    bad_request: 400
    ok: 200

  datasource:
    url: jdbc:mariadb://localhost:3306/greenfin_fund_transfer_service
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true