spring:
  application:
    name: sequence-generator

  datasource:
    url: jdbc:mariadb://localhost:3306/greenfin_sequence_generator
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8083
